[package]
name = "blinky-unsafe-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.7"
panic-halt = "0.2"


[profile.release]
debug = 2
# debug = true
# lto = true
